# Generated by Django 2.1.7 on 2019-02-14 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=25)),
                ('harga', models.CharField(max_length=50)),
                ('waktuTersedia', models.DateField(default=django.utils.timezone.now)),
                ('gambar', models.ImageField(upload_to='home')),
                ('penulis', models.CharField(max_length=50)),
            ],
        ),
    ]
