# Generated by Django 2.1.7 on 2019-02-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_buku_hargadiskon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='waktuTersedia',
        ),
        migrations.AddField(
            model_name='buku',
            name='ketersediaan',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buku',
            name='publisher',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buku',
            name='kategori',
            field=models.CharField(max_length=50),
        ),
    ]
