# Generated by Django 2.1.7 on 2019-02-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20190214_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='sinopsis',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
