# Generated by Django 2.1.7 on 2019-02-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='kategori')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('ketersediaan', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('hargadiskon', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
    ]
