# Generated by Django 2.1.7 on 2019-02-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kategori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commedy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='kategori')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('ketersediaan', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('hargadiskon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='kategori')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('ketersediaan', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('hargadiskon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='horror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='kategori')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('ketersediaan', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('hargadiskon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='romance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='kategori')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('ketersediaan', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('hargadiskon', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='kategori',
        ),
    ]
