# Generated by Django 2.1.7 on 2019-02-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kategori', '0002_auto_20190214_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commedy',
        ),
        migrations.DeleteModel(
            name='fiction',
        ),
        migrations.DeleteModel(
            name='romance',
        ),
    ]
