# Generated by Django 2.1.7 on 2019-02-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kategori', '0003_auto_20190214_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horror',
            name='hargadiskon',
        ),
    ]
