# Generated by Django 2.1.7 on 2019-02-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kategori', '0005_horror_hargadiskon'),
    ]

    operations = [
        migrations.AddField(
            model_name='horror',
            name='kategori',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
