# Generated by Django 2.1.7 on 2019-02-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kategori', '0006_horror_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='nonfiksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='kategori')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('ketersediaan', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('hargadiskon', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='romance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='kategori')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('ketersediaan', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('hargadiskon', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sastra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='kategori')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('ketersediaan', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('hargadiskon', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='teknik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='kategori')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('ketersediaan', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('hargadiskon', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='horror',
            new_name='agama',
        ),
    ]
